### ISSUE TITLE
how to extend the co-simulation environment

### ISSUE THREAD

**Issue by zgq91** [zhangzhizza/Gym-Eplus#2]
Hi:
   张博您好,我想控制生产车间的温度如何扩展冷却水温度,冷冻水温度,冷冻水质量流量,室内温湿度,室外温湿度等因素的仿真环境

**Comment by zhangzhizza** [comment]
你好，你需要建立一个EnergyPlus模型，通过EnergyPlus ExternalInterface的功能暴露冷却水温度,冷冻水温度,冷冻水质量流量,室内温湿度,室外温湿度这些参数（具体参考：https://bigladdersoftware.com/epx/docs/8-3/external-interfaces-application-guide/bcvtb-examples.html）。这个Gym-Eplus仅仅是对已经建好了的EnergyPlus模型的Python封装而已。
