### ISSUE TITLE
What are the terms in the observation?

### ISSUE THREAD

**Issue by Junxi-Chen** [zhangzhizza/Gym-Eplus#3]
Hi,张博士您好:
想问您一下，在observation里面的15个观测量都分别是什么？看您的论文 里面15个观测量并没发按顺序和环境给出的观测值一一对应上。或者您可以告诉我在哪里可以看到相关信息呢，万分感谢🙏

**Comment by zhangzhizza** [comment]
论文里的模型不在这个repo里，这个repo只是基本的co-sim脚本而已。论文里的模型在https://github.com/zhangzhizza/HVAC-RL-Control/tree/a3c/src/eplus-env/eplus_env/envs/eplus_models/iw_v96/learning/cfg （这个repo比较乱，没时间整理，所以就没放到论文里）。具体这些observation都是什么意思，在https://www.sciencedirect.com/science/article/abs/pii/S0378778818330858 的table8

**Comment by Junxi-Chen** [comment]
非常感谢老师的回答！但我还是存在不明白的地方。在reset后，环境给的我第一组反馈量是[1.8, 95.25, 4.1, 265.0, 0.0, 0.0, 20.0, 60.0, 20.09252097771263, 18.99715464524551, 41.66961990729963, 0.7499999951999999, 31.75714300306873, 0.0, 5683.861879933708]。但显然第二个观察量95.25并不是Hour of the day，我并不能找到他们之间逐项明确的对应关系。我想根据您的思路做一下关于空调控制优化的强化学习实验。不知道您有没有比较方便的实验环境推荐，不求功能全面，可以提供python借口，让我开始实验就可以，非常感谢您！

**Comment by zhangzhizza** [comment]
这个repo里的环境和论文里使用的模型没有任何关系。实验模型你可以用DOE的reference model，但是环境输入输出的配置需要你自己根据情况去做，目前还没有一个业内统一的benckmark环境。至于两个时间变量，他们不是energyplus的直接输出，是需要你自己通过curSimTime（当前仿真时间，单位是秒）来计算得到。这个repo里的示例环境，用的就是一个DOE reference model的small office，输入输出的配置在这里https://github.com/zhangzhizza/Gym-Eplus/blob/master/eplus_env/envs/eplus_models/demo_5z/learning/cfg/variables_v0.cfg

论文里的代码都在这个https://github.com/zhangzhizza/HVAC-RL-Control/tree/a3c repo里，但是我没有整理，也没有文档。9月份我可能有时间会整理一下。

**Comment by Junxi-Chen** [comment]
谢谢您的解答！
